### PR TITLE
Create maven.yml

### PR DESCRIPTION
**Pull request by pbutti**
Create a continuous integration yaml file for automatic compilation of master. 
Automatic running of tests will be added soon

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
This is possibly useful but I think it needs to be discussed first...

**Comment by pbutti** [comment]
Hey Jeremy,

thanks for taking a look. Well, at the moment is super basic and checks just the compilation. It also runs the tracking tests (but we should improve that). The fact is that is so basic, that I think doesn't need too much of a discussion in my view. But of course, happy to discuss together =)

Cheers,
PF

**Comment by JeremyMcCormick** [comment]
```
   - name: Run hps-java tests
      run: mvn test
```

I do not think this is the correct way to run the tests. You would just do `mvn install` with no `skipTests` option, instead, though I would be surprised if this even works on the server where this would be run.

**Comment by pbutti** [comment]
Hi Jeremy, 

yeah. The second automatic test should be removed, the compilation seems to run OK. Would you be ok to add the compilation part only?

**Comment by JeremyMcCormick** [comment]
> Hi Jeremy,
> 
> yeah. The second automatic test should be removed, the compilation seems to run OK. Would you be ok to add the compilation part only?

I am inclined to approve the compilation check by itself without any tests. It is a good sanity check on PRs, I think, and shouldn't cause any issues.

**Review by JeremyMcCormick — DISMISSED** [review]
I will approve after build with tests is changed to:

```
mvn clean install
```

**Comment by cbravo135** [comment]
I agree with Jeremy, `mvn test` does not run all the tests. It only does a few of them, not clear to me at this time how it decides which ones to run. It might only be running the unit tests within the modules, but it seems to skip all of the integration-tests.

**Comment by JeremyMcCormick** [comment]
It should be 'mvn verify' from the integration-tests dir to run the ITs

**Comment by normangraf** [comment]
`mvn clean install` is the correct procedure to build and run all the relevant tests.

**Comment by pbutti** [comment]
Changed are in. Checks have passed. Other stoppers?

**Comment by JeremyMcCormick** [comment]
> Changed are in. Checks have passed. Other stoppers?

Have you actually confirmed that the tests run successfully in the github build environment?

**Comment by JeremyMcCormick** [comment]
> Changed are in. Checks have passed. Other stoppers?

Does this mean that the tests all ran successfully? If so how did you verify this? (Do you have a link showing they ran okay?)

Is there a way to actually see the test output easily?

**Comment by pbutti** [comment]
click on the v next to the commit,  then click on "details", then expand "build hps-java and run tests", scroll down to the end of a long log and you see the results. Here copy pasted

esults :

Tests run: 19, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ hps-integration-tests ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hps-integration-tests ---
[INFO] Installing /home/runner/work/hps-java/hps-java/integration-tests/target/hps-integration-tests-4.5-SNAPSHOT.jar to /home/runner/.m2/repository/org/hps/hps-integration-tests/4.5-SNAPSHOT/hps-integration-tests-4.5-SNAPSHOT.jar
[INFO] Installing /home/runner/work/hps-java/hps-java/integration-tests/pom.xml to /home/runner/.m2/repository/org/hps/hps-integration-tests/4.5-SNAPSHOT/hps-integration-tests-4.5-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for HPS Java 4.5-SNAPSHOT:
[INFO] 
[INFO] HPS Java ........................................... SUCCESS [02:15 min]
[INFO] logging ............................................ SUCCESS [ 41.031 s]
[INFO] util ............................................... SUCCESS [  2.203 s]
[INFO] detector-data ...................................... SUCCESS [ 43.463 s]
[INFO] conditions ......................................... SUCCESS [  2.167 s]
[INFO] detector-model ..................................... SUCCESS [ 17.940 s]
[INFO] record-util ........................................ SUCCESS [ 12.790 s]
[INFO] datacat ............................................ SUCCESS [ 15.751 s]
[INFO] run-database ....................................... SUCCESS [  0.790 s]
[INFO] ecal-recon ......................................... SUCCESS [  0.928 s]
[INFO] ecal-readout-sim ................................... SUCCESS [  1.438 s]
[INFO] tracking ........................................... SUCCESS [ 40.991 s]
[INFO] recon .............................................. SUCCESS [  1.111 s]
[INFO] analysis ........................................... SUCCESS [01:03 min]
[INFO] crawler ............................................ SUCCESS [  0.641 s]
[INFO] job ................................................ SUCCESS [  0.313 s]
[INFO] evio ............................................... SUCCESS [  0.734 s]
[INFO] monitoring-util .................................... SUCCESS [  5.127 s]
[INFO] ecal-event-display ................................. SUCCESS [  1.322 s]
[INFO] monitoring-drivers ................................. SUCCESS [  0.872 s]
[INFO] steering-files ..................................... SUCCESS [ 41.270 s]
[INFO] monitoring-app ..................................... SUCCESS [  0.621 s]
[INFO] online-recon ....................................... SUCCESS [  1.604 s]
[INFO] distribution ....................................... SUCCESS [ 14.791 s]
[INFO] plugin ............................................. SUCCESS [  6.625 s]
[INFO] integration-tests .................................. SUCCESS [42:03 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47:50 min (Wall Clock)
[INFO] Finished at: 2021-02-05T06:32:44Z
[INFO] ------------------------------------------------------------------------

**Review by cbravo135 — APPROVED** [review]

**Review by JeremyMcCormick — APPROVED** [review]
Looks like a nice addition

**Pull request merged**
