### PR TITLE
Kalman dev

### PR DESCRIPTION
**Pull request by pbutti**
Kalman dev

### CODE REVIEW

**Comment by cbravo135** [comment]
This branch is quite a bit behind master at the moment. Please consider pulling master and rerunning your checks to make sure everything is still good after merging in the current master. git will be able to merge automatically via the normal recursive strategy, so don't worry about that (I already did this). I am currently running a few checks of this myself.

**Comment by pbutti** [comment]
Hi Cam, 

Thank you for checking this!
I don't think it's necessary to pull master, merge locally and rerun, as only these 3 commits are added to the master. The difference with master are already shows by the PR, and that's what matters. The kalman_dev Will be the same as master after the merge.

**Review by cbravo135 — APPROVED** [review]
I ran a few files with this and iss837, and master all merged. Look reasonable to me. I also checked that is passes the integration tests.

**Comment by cbravo135** [comment]
The results from running on the 2019 sample partitions, currently at [https://www.slac.stanford.edu/~bravo/KF_vs_GBL_Tight_pBot_2019/KF_vs_GBL_Tight_pBot_2019.html ](https://www.slac.stanford.edu/~bravo/KF_vs_GBL_Tight_pBot_2019/KF_vs_GBL_Tight_pBot_2019.html ) use these three commits.

**Review by normangraf — APPROVED** [review]
This adds new functionality and fixes a few known issues.
Does not affect legacy reconstruction.
Code builds and tests pass.
Please proceed.

**Pull request merged**
