### PR TITLE
Iss400: Add unbiased hit residual code

### PR DESCRIPTION
**Pull request by mrsolt**
Adding unbiased hit residual code. And updating some SVT hit level plot code.

### CODE REVIEW

**Comment by normangraf** [comment]
Should this have a unit/integration test to check residuals?

**Comment by normangraf** [comment]
Integration tests fail. It appears that this branch is not up to date with the master.

**Comment by mrsolt** [comment]
Does the tracking/src/main/java/org/hps/svt/SVTHitLevelPlots.java<https://github.com/JeffersonLab/hps-java/pull/429/files#diff-a63b56084f2a3729963bfbd58d054610> have integration tests? I made some changes to those so it might fail there. My unbiased residual code is separate, and probably should be added to the integration tests.


Matt Solt

________________________________

**Review by normangraf — APPROVED** [review]
This should build cleanly once it's merged with master.

**Review by bloodyyugo — COMMENTED** [review]
I've been using this and it works!

**Review by bloodyyugo — APPROVED** [review]

**Pull request merged**
