### PR TITLE
add a steering file for overlaying MC signal with pulser data

### PR DESCRIPTION
**Pull request by tongtongcao**
A steering file for overlay MC signal with pulser data was developed.
Additionally, readout steering file with signal-pulserData as input was slight changed.

### CODE REVIEW

**Review by cbravo135 — APPROVED** [review]
We should discuss what exactly we would like to see as validation for this. I am interested in seeing a comparison of our beam background MC and random triggers. Does this really only use pulser events from data or does it also use the faraday cup sourced random triggers? We should be able to use both, maybe do a quick comparison of the two to be sure they both appear to have zero bias. We might also want to look at some physics selections with beam background and compare to this, and see how close things look. This all being said, I am approving this because it is just adding some new steering files and not changing the production steering files.

**Comment by tongtongcao** [comment]
> We should discuss what exactly we would like to see as validation for this. I am interested in seeing a comparison of our beam background MC and random triggers. Does this really only use pulser events from data or does it also use the faraday cup sourced random triggers? We should be able to use both, maybe do a quick comparison of the two to be sure they both appear to have zero bias. We might also want to look at some physics selections with beam background and compare to this, and see how close things look. This all being said, I am approving this because it is just adding some new steering files and not changing the production steering files.



> We should discuss what exactly we would like to see as validation for this. I am interested in seeing a comparison of our beam background MC and random triggers. Does this really only use pulser events from data or does it also use the faraday cup sourced random triggers? We should be able to use both, maybe do a quick comparison of the two to be sure they both appear to have zero bias. We might also want to look at some physics selections with beam background and compare to this, and see how close things look. This all being said, I am approving this because it is just adding some new steering files and not changing the production steering files.

Quickly answer the questions:
We did preliminary study to compare signal + pulser data to signal + MC beam, which were reported in several meetings. With loose kinematic cuts, they are basically consistent. One thing we are not clear is that MC beam has much higher FEE peak than pulser data.
For software itself, it does not care what random data as input. It is our choice to use what random data.
For the test study, random data with DAQ hps_v11_5_random_15kHz.cnf is applied.

**Comment by JeremyMcCormick** [comment]
Noted Tongtong's answers to Cam's questions. This looks like steering files only and safe to merge.

**Review by JeremyMcCormick — APPROVED** [review]
Steering file only - looks safe.

**Pull request merged**
