### PR TITLE
Iss420: Hodoscope Software Updates

### PR DESCRIPTION
**Pull request by mccaky**
@mholtrop Please use the **squash** option when merging this so that all the different commits are not spread out all over the log by date.  Thanks!

---

The bulk of the hodoscope readout chain is prepared for verification. This includes the preprocessing driver, the digitization driver, and the raw converter driver. There is also a "dump" hodoscope trigger that is intended for use in trigger studies.

The hodoscope-specific drivers that need checking include:

- `HodoscopePreprocessingDriver`
- `HodoscopeDigitizationReadoutDriver`
- `HodoscopeRawConverterReadoutDriver`
- `HodoscopeReadoutMode3RawConverter`
- `HodoscopeStudiesTriggerReadoutDriver`

Additionally, changes were made to the digitization driver that also affect the calorimeter. Thus, the drivers

- `DigitizationReadoutDriver`
- `EcalDigitizationReadoutDriver`

should also be checked. In this case, it is probably sufficient to verify that `EcalDigitizationReadoutDriver` functions identically to the old digitization readout driver. The bulk of the code is not really different. The subdetector-specific portions have just been abstracted out of `DigitizationReadoutDriver` and then re-implemented in `EcalDigitizationReadoutDriver`.

Further, it would be useful to review `org.hps.readout.rawconverter` in the `ecal-readout-sim` package. This was a necessary restructuring of the old raw converters to simplify and remove the bloat that had built up in the original version. It was not feasible to perform a similar abstraction of subdetector-specific behavior in a reasonable fashion in the original. Only the `HodoscopeReadoutMode3RawConverter` and `EcalReadoutMode3RawConverter` are actually used at the present. The latter should function identically to the previous raw converter during readout. The other drivers are implemented with the intent that can be used for reconstruction and, ideally, to replace the existing overly complicated raw converters. However, these have not been tested. As such, the old raw converters are retained and remain in place in reconstruction steering files. At least `HodoscopeMode1RawConverter` is likely to be necessary in some form for hodoscope reconstruction, though.

Lastly, the `org.hps.analysis.util` package has a few utilities (and helper classes) vaguely relevant to the hodoscope. These can be reviewed as well, though they appear to be working as intended. These are not necessary for the hodoscope readout functionality and can be excluded from the merge if desired.

Lastly, because some calorimeter code was changed, it is important to verify that the steering files still work properly.

The hodoscope trigger studies readout may be run with the steering file `SimpleHodoscopeTriggerNoTracker`. This will not make use of any SVT objects or data, but will run the full calorimeter and hodoscope readout. It uses the trigger studies simple trigger. Additionally, the driver `HodoscopePlotsDriver` creates a number of distributions for input and output objects during readout. The command line argument to run the code is:

`java -DdisableSvtAlignmentConstants=true -jar $HPS_JAVA_420 $STEERING -i $INPUT -DoutputFile=$OUTPUT_FILENAME -d $DETECTOR -R $RUN_NUMBER`

The default parameters are `HPS-HodoscopeTest-v1` for the detector name and `1000000` for the run number. The working steering file is `SimpleHodoscopeTriggerNoTracker`, which is available in the standard readout steering file repository in the issue.

Also of potential use are the commands:

- `java -cp $HPS_JAVA_420 org.hps.analysis.util.HodoscopeBoundsPrinterUtility -d  $DETECTOR_NAME   -R $RUN_NUMBER`
- `java -cp $HPS_JAVA_420 org.hps.analysis.util.HodoscopeChannelConditionsUtility -d $DETECTOR_NAME -R  $RUN_NUMBER`

The first will print out the bounds of each scintillator as well as the position(s) of its optical fiber hole(s) for a given geometry run number. The latter will print the conditions for each channel for a given geometry and run number.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
There is an integration test for this branch here:

```
integration-tests/src/test/java/org/hps/test/it/HodoscopeReadoutTest.java
```

It can be run as follows:

```
cd integration-tests; mvn verify -Dit.test=HodoscopeReadoutTest
```

The test case does not have any assertions but it will produce plots to the output file:

```
target/test-output/HodoscopeReadoutTest/HodoscopeReadoutTest.aida
```

Two sets of plots can be generated using this test case.

To enable the basic set of plots, set this constant to true in the Java file:

```
INCLUDE_BASIC_PLOTS
```

To enable the detailed plots, set this constant to true:

```
INCLUDE_DETAILED_PLOTS
```

If you as a reviewer have inserted any new plots or debug statements and just want to rerun the analysis without redoing the filtering or readout steps (which take quite a while to run), then set both the constants `RUN_READOUT` and `RUN_FILTERING` to `false` and the existing outputs will be used.

**Comment by JeremyMcCormick** [comment]
@mccaky Do you have any plots which show before/after of the ECal output from readout, just as a sanity check?

Would it also make sense to add some plots having to do with times of the output objects, especially since this is one of the more complicated parts of the readout simulation?

EDIT: I noticed that all the time values of the output hit objects are zero for both ECal and Hodoscope.  Is this working as intended?

**Comment by rafopar** [comment]
Hi @JeremyMcCormick and @mccaky 

The code didn't compile when when I compile without `-DskipTests`, though it compiles when I skip tests.
Is iss420 this expected behavior? though the error is related to tracking

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.hps.recon.tracking.ComparisonTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.279 sec <<< FAILURE! - in org.hps.recon.tracking.ComparisonTest
testRecon(org.hps.recon.tracking.ComparisonTest)  Time elapsed: 10.251 sec  <<< ERROR!
java.net.SocketTimeoutException: Read timed out
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
etc etc etc

**Comment by JeremyMcCormick** [comment]
> Hi @JeremyMcCormick and @mccaky
> 
> The code didn't compile when when I compile without `-DskipTests`, though it compiles when I skip tests.
> Is iss420 this expected behavior? though the error is related to tracking
> 
> ## T E S T S
> Running org.hps.recon.tracking.ComparisonTest
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.279 sec <<< FAILURE! - in org.hps.recon.tracking.ComparisonTest
> testRecon(org.hps.recon.tracking.ComparisonTest) Time elapsed: 10.251 sec <<< ERROR!
> java.net.SocketTimeoutException: Read timed out
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> etc etc etc

Probably it compiled but just one of the tests failed.  Maybe nothing to worry about for this PR.

**Comment by JeremyMcCormick** [comment]
> java.net.SocketTimeoutException: Read timed out

This indicates a problem reading a file over the internet.  I don't think it is at all related to any changes on this branch.

**Comment by rafopar** [comment]
Ok, thanks, it happened with the master branch as well.

**Comment by rafopar** [comment]
> Probably it compiled but just one of the tests failed. Maybe nothing to worry about for this

Just to answer above, seems it didn't compile see below, but yes I agree it is not related to iss420

[INFO] datacat ............................................ SUCCESS [  0.287 s]
[INFO] run-database ....................................... SUCCESS [  0.303 s]
[INFO] ecal-recon ......................................... SUCCESS [  0.671 s]
[INFO] ecal-readout-sim ................................... SUCCESS [  0.488 s]
[INFO] tracking ........................................... FAILURE [ 32.518 s]
[INFO] recon .............................................. SKIPPED
[INFO] analysis ........................................... SKIPPED
[INFO] crawler ............................................ SKIPPED
[INFO] job ................................................ SKIPPED

**Comment by rafopar** [comment]
`java -DdisableSvtAlignmentConstants=true -jar $HPS_JAVA_420 $STEERING -i $INPUT -DoutputFile=$OUTPUT_FILENAME -d $DETECTOR -R $RUN_NUMBER`

@mccaky , Could you point me to any file that I can use as an $INPUT here

**Comment by JeremyMcCormick** [comment]
> `java -DdisableSvtAlignmentConstants=true -jar $HPS_JAVA_420 $STEERING -i $INPUT -DoutputFile=$OUTPUT_FILENAME -d $DETECTOR -R $RUN_NUMBER`
> 
> @mccaky , Could you point me to any file that I can use as an $INPUT here

No real need to run this command.  You can just use the test case.

https://github.com/JeffersonLab/hps-java/pull/471#issuecomment-491207725

**Comment by rafopar** [comment]
Thanks @JeremyMcCormick ,

it didn't compile again,it gives similar error on timeout now hodoscope repalted.

Can you try to reproduce this?
I am running from my local computer, and I have an internet connections

This is the output of the following command

`mvn verify -Dit.test=HodoscopeReadoutTest`

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.hps.test.it.HodoscopeReadoutTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.246 sec <<< FAILURE! - in org.hps.test.it.HodoscopeReadoutTest
testHodoscopeReadout(org.hps.test.it.HodoscopeReadoutTest)  Time elapsed: 10.134 sec  <<< ERROR!
java.net.SocketTimeoutException: Read timed out
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by mccaky** [comment]
Hi @JeremyMcCormick and @rafopar,

I've just been using a no-SVT sample file, but with spacing, that Jeremy gave me a ways back for input. Any data file created with the up-to-date version of the HPS-HodoscopeTest-v1 detector should work, though. The file is too big to upload here, and apparently my JLab password expired, so I've uploaded it to the UNH servers at "/net/home/mccaky/slicHodoTestEvents.slcio" pending getting my account fixed so at least Rafo can access it. Please note that the file will need to be spaced.

Concerning the steering file command, this should be run and tested. It's what we'll actually be using for trigger studies and also produces a number of plots, some of which can not be created except _during_ readout, since it uses objects that are not persisted into LCIO. I do strongly encourage testers to actually run the steering file.

**Comment by mccaky** [comment]
Hi @JeremyMcCormick,

Regarding calorimeter plots, no, I do not create any. I only added in detailed plots for the hodoscope.

Concerning readout hits for the calorimeter/hodoscope, it is working as intended that they all have a time of `t = 0`. These objects are ADC buffers, and the hit time is extrapolated during raw conversion from the ADC pulse during reconstruction.

**Comment by rafopar** [comment]
> java -cp $HPS_JAVA_420 org.hps.analysis.util.HodoscopeBoundsPrinterUtility -d $DETECTOR_NAME -R $RUN_NUMBER
java -cp $HPS_JAVA_420 org.hps.analysis.util.HodoscopeChannelConditionsUtility -d $DETECTOR_NAME -R $RUN_NUMBER

Output of above commands, is correct.
They printout positions of hodo tiles and hodo conditions.

**Comment by rafopar** [comment]
Hi @JeremyMcCormick and @mccaky 
Ok, now the command `mvn verify -Dit.test=HodoscopeReadoutTest` works

I am looking into the output aida file,
could you comment on what is the difference between hits at the which are distributed uniformly along z inside the hodo tile, and and hits which are at the center of the tile

image

**Comment by normangraf** [comment]
The integration tests (including the 2015 and 2016 physics analyses) are now completing successfully.

**Review by normangraf — APPROVED** [review]
I have not completed an in-depth review of the code, but the code builds and all tests pass, so I believe we should go live with this so further testing and analysis can proceed.

**Comment by normangraf** [comment]
Output from the HodoscopeStudiesTriggerReadoutDriver should be suppressed.

**Comment by normangraf** [comment]
Spoke too soon. One test is failing, viz.

Tests in error:
  HodoscopeSimDataTest.testHodoscopeData:53
Caused by: java.lang.StackOverflowError
        at org.hps.detector.hodoscope.HodoscopeDetectorElement.getScintillatorPosition(HodoscopeDetectorElement.java:306)

**Comment by mholtrop** [comment]
Yes, I saw that too. 
Are you also getting the following error? Are these related?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.maven.surefire.shade.org.apache.maven.shared.utils.xml.Xpp3DomBuilder (file:/Users/maurik/.m2/repository/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.jar) to constructor com.sun.org.apache.xerces.internal.parsers.SAXParser()
WARNING: Please consider reporting this to the maintainers of org.apache.maven.surefire.shade.org.apache.maven.shared.utils.xml.Xpp3DomBuilder
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Review by mholtrop — APPROVED** [review]
Last commit by Kyle fixed last problem with the tests. This can go into master now.

**Comment by JeremyMcCormick** [comment]
Unrelated and doesn't matter at all (just a warning).

**Pull request merged**
