### PR TITLE
Fix the Hodo monitoring

### PR DESCRIPTION
**Pull request by rafopar**
The Hodo hit collection is not 'SimpleGenericObject' anymore, but rather 'CalorimeterHit', The collection name is changed, and variable asignment satememts also changed.

### CODE REVIEW

**Comment by rafopar** [comment]
It worked for me after those changes.

**Comment by bloodyyugo** [comment]
It almost works!  For "matched hit energies" only one plot is filling and it has a lot of 0s for some reason...

**Comment by rafopar** [comment]
Yes that is correct.

Others were not present event in the 2019 run.

It was more of diagnostic, just was testing something.
Later if I will have time, will popolate others as well, but it is not critical.

**Review by bloodyyugo — APPROVED** [review]
Looks good, thanks Rafo

**Comment by normangraf** [comment]
Does this cause any problems of backwards-compatibility with the 2019 data?

**Comment by rafopar** [comment]
No, I have tested this on 2019 data.

Before the reconstruction was making genericobjects for Hodo hits, now the recon produces Calorimeter hits, so accordingly I had to change the monitoring app to read from Calorimeter hits, instead of the genericObject.

**Comment by bloodyyugo** [comment]
Probably for lcio files written before Maurik's changes (when?) but running from evio it's fine.

**Comment by rafopar** [comment]
Yes, slcio file format got different.
I believe this change happened by the end of 2019, or early 2020.

Yes it is fine with EVIO.

**Review by normangraf — APPROVED** [review]
Looks good. Please proceed.

**Comment by rafopar** [comment]
Thanks

**Pull request merged**
