### PR TITLE
removed some tests in analysis module

### PR DESCRIPTION
**Pull request by normangraf**
I've disabled the two failing tests in analysis and updated the reference histograms for the integration tests. The mast should now build and test cleanly. Please test the complete build before approving this pull request.

### CODE REVIEW

**Comment by mholtrop** [comment]
On both the MacOS and Linux Lentos 7 machines the test still fail. Results from Linux:
```Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 23.679 sec - in org.hps.test.it.EvioToLcioTest

Results :

Failed tests: 
  EngRun2015FeeReconTest.testIt:67->comparePlots:107 expected:<1.2783774159754366> but was:<1.2794887170090619>
  EngRun2015MollerReconTest.testIt:62->comparePlots:103 expected:<5.128157963170287> but was:<5.1301620897750295>
  EngRun2015V0ReconTest.testIt:66->comparePlots:105 expected:<1950> but was:<1949>
  PhysRun2016FeeReconTest.testIt:62->comparePlots:89 expected:<124> but was:<125>
  PhysRun2016MollerReconTest.testIt:66->comparePlots:93 expected:<2223> but was:<2221>
  PhysRun2016V0ReconTest.testIt:66->comparePlots:93 expected:<4892> but was:<4890>
```

**Comment by normangraf** [comment]
Thanks Maurik. What version of java were you using? (not that it should matter, but...)

**Comment by bloodyyugo** [comment]
Yeah, I see same as Maurik using: 

[Benny:~/hps/hps-java-HEAD] %java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

**Comment by normangraf** [comment]
Thanks Matt. That's also what I see on my PC. Seems SLAC linux is odd man out.

**Comment by mholtrop** [comment]
On Linux: java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

On MacOS: java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

Errors are the same on these systems, so it is not the Java version. Also, on both systems I first removed .m2, so everything was downloaded anew.

**Comment by normangraf** [comment]
OK, thanks.

**Comment by normangraf** [comment]
I have updated the reference plots. Could you please confirm that the release now builds successfully? You do not need to rebuild and test everything. The following should suffice:

cd integration-tests
mvn verify

**Comment by baltzell** [comment]
These tests now pass for me (FWIW, with openjdk 11.0.8)

Screen Shot 2020-10-28 at 5 51 01 PM

Also, it seems like there should be a slow and fast version of these tests.

**Review by baltzell — APPROVED** [review]

**Review by bloodyyugo — APPROVED** [review]
Tests succeed for me now...

**Pull request merged**
