### PR TITLE
Iss 928

### LINKED ISSUE #928: ECAL position corrections for 2021
Check the ECAL position corrections for 2021 run. There can be some differences between 2019 and 2021 due to the different magnetic field value (for a given energy, 2019 / 2021 differ in the impact angle on the ECAL front face)

Plan:

- Start from the 2019 approach
- Check the results
- Correct if necessary

### PR DESCRIPTION
**Pull request by andrea-celentano**

### CODE REVIEW

**Comment by andrea-celentano** [comment]
This should close the 2021 position corrections - they were still to be finished (my fault!).

**Comment by andrea-celentano** [comment]
Ok, this is really annoying. I got an error in the compilation regarding some weird "code style":

image



I am using Eclipse for code development, and in the confluence page: https://confluence.slac.stanford.edu/display/hpsg/Project+Development+in+Eclipse#ProjectDevelopmentinEclipse-ProjectSourceCodeFormatting 
nothing is reported about - I already implemented the "spaces only" policy.

**I am not going to spend any time in fixing this.**

**Comment by cbravo135** [comment]
Thank you @mholtrop for linting this!

**Review by normangraf — APPROVED** [review]
These changes result in an improvement in the track-cluster matching of FEEs of a little over 0.5mm. Looks good, please proceed.

**Review by cbravo135 — APPROVED** [review]
Hardcoded constants updated in 2021 ecal cluster position correction.

**Pull request merged**
