### PR TITLE
MOUSE

### PR DESCRIPTION
**Pull request by mdiamon**
Object Standardization

### CODE REVIEW

**Comment by mdiamon** [comment]
Combined with #328

**Comment by JeremyMcCormick** [comment]
You should setup your StandardCuts class in the detectorChanged() or startOfData() methods instead of in the setters.  Beam energy will have been set by then so you don't need to do this in multiple places.

**Comment by mholtrop** [comment]
Passed all the tests. Yay!

**Review by mholtrop — APPROVED** [review]
All tests passed, seems good to go.

**Pull request merged**
