### PR TITLE
Iss410: Vertexing and Tracking Fixes

### PR DESCRIPTION
**Pull request by bloodyyugo**
This branch: 
1) fixes the beamspot constrained fit/covariance when the reference point is shifted
2) fixes the number of degrees of freedom of vertex fits
3) includes the rf/highest energy Eal cluster SVT hit referencing from issue 404 (I'll rescind the pull request for that one)
4) adds some more saved parameters into the BilliorVertex object so that they can be used in the DST

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
IT output changes:

```
checking entries, means and rms for ./BeamspotConstrainedV0Vertices/V0 Bottom Track Momentum
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 202.337 sec <<< FAILURE! - in org.hps.test.it.EngRun2015V0ReconTest
testIt(org.hps.test.it.EngRun2015V0ReconTest)  Time elapsed: 202.289 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<1906> but was:<1873>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at org.hps.test.it.EngRun2015V0ReconTest.comparePlots(EngRun2015V0ReconTest.java:105)
	at org.hps.test.it.EngRun2015V0ReconTest.testIt(EngRun2015V0ReconTest.java:66)
```

```
checking entries, means and rms for ./BeamspotConstrainedV0Vertices/V0 Bottom Track Momentum
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 434.784 sec <<< FAILURE! - in org.hps.test.it.PhysRun2016V0ReconTest
testIt(org.hps.test.it.PhysRun2016V0ReconTest)  Time elapsed: 434.655 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<4903> but was:<4803>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at org.hps.test.it.PhysRun2016V0ReconTest.comparePlots(PhysRun2016V0ReconTest.java:93)
	at org.hps.test.it.PhysRun2016V0ReconTest.testIt(PhysRun2016V0ReconTest.java:66)
```

```
checking entries, means and rms for ./BeamspotConstrainedMollerVertices/Moller Bottom Track Momentum
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 643.006 sec <<< FAILURE! - in org.hps.test.it.EngRun2015MollerReconTest
testIt(org.hps.test.it.EngRun2015MollerReconTest)  Time elapsed: 642.901 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<475> but was:<469>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at org.hps.test.it.EngRun2015MollerReconTest.comparePlots(EngRun2015MollerReconTest.java:101)
	at org.hps.test.it.EngRun2015MollerReconTest.testIt(EngRun2015MollerReconTest.java:62)
```

**Comment by JeremyMcCormick** [comment]
@bloodyyugo 

This print out needs to be commented out or put inside a debug switch.

```
tracking/src/main/java/org/hps/recon/tracking/RawTrackerHitFitterDriver.java:151:                System.out.println("Getting TriggerTime Object");
```

It is printing many times for every event when running the recon!

**Comment by JeremyMcCormick** [comment]
@bloodyyugo 

There's a test failure introduced by these changes.

https://srs.slac.stanford.edu/hudson/view/HPS/job/hps-java-dev/lastBuild/org.hps$hps-analysis/testReport/org.hps.analysis/TridentTupleDriverTest/testIt/

```
Caused by: java.lang.NullPointerException
	at org.hps.recon.vertexing.BilliorVertex.getParameters(BilliorVertex.java:274)
	at org.hps.analysis.tuple.TupleMaker.fillVertexVariables(TupleMaker.java:1214)
	at org.hps.analysis.tuple.TupleMaker.fillBasicTuple(TupleMaker.java:340)
	at org.hps.analysis.tuple.TridentTupleDriver.process(TridentTupleDriver.java:34)
```

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
- Remove debug print

- Fix test failure listed in comments (NullPointerException)

- REMINDER: Update the AIDA ref histograms by providing them to Norman (can be done after merging)

**Comment by JeremyMcCormick** [comment]
@bloodyyugo 

I confirmed that the `NullPointerException` is fixed.

I pushed some minor edits to remove the debug print out, as it was still there when I checked.

As before, the recon ITs are failing, because slightly fewer bottom tracks are being found now.

This shows the differing number of entries between the reference plots and the output from this branch, corresponding to the number of bottom tracks:

```
Failed tests:
  EngRun2015MollerReconTest.testIt:62->comparePlots:101 expected:<475> but was:<469>
  EngRun2015V0ReconTest.testIt:66->comparePlots:105 expected:<1906> but was:<1873>
  PhysRun2016FeeReconTest.testIt:62->comparePlots:89 expected:<129> but was:<124>
  PhysRun2016MollerReconTest.testIt:66->comparePlots:93 expected:<2595> but was:<2459>
  PhysRun2016V0ReconTest.testIt:66->comparePlots:93 expected:<4903> but was:<4803>
```

Assuming this change of roughly 1% fewer bottom tracks is expected, @normangraf normally handles updating the reference histograms, and he is out of town for a few weeks.  I would rather not break the integration tests on the master, as it useful that they pass for verifying changes.  So we should either hold off on merging until he is back, or someone else should update these files before he returns.

I'll add my approval once the ref histogram issue is discussed/resolved.

**Comment by bloodyyugo** [comment]
Failed tests:
  EngRun2015MollerReconTest.testIt:62->comparePlots:101 expected:<475> but was:<469>
  EngRun2015V0ReconTest.testIt:66->comparePlots:105 expected:<1906> but was:<1873>
  PhysRun2016FeeReconTest.testIt:62->comparePlots:89 expected:<129> but was:<124>
  PhysRun2016MollerReconTest.testIt:66->comparePlots:93 expected:<2595> but was:<2459>
  PhysRun2016V0ReconTest.testIt:66->comparePlots:93 expected:<4903> but was:<4803>


@bloodyyugo<https://github.com/bloodyyugo> can you verify the changes to the recon output

Yeah, this is all consistent with what I see.  Do you know when Norman gets back?  We need to get this in before we recon the 2016 MC and re-recon the V0 skims.



@normangraf<https://github.com/normangraf> normally handles updating the reference histograms that check the recon output, and he is out of town for a few weeks. I would rather not break the integration tests on the master, so we should either hold off on merging until he is back or someone else should update them.

**Comment by JeremyMcCormick** [comment]
@bloodyyugo

If this is expected we can work on updating the ref plots.  I don't think Norman is back until around April 15.

**Comment by bloodyyugo** [comment]
Yeah, this is expected…how do we replace plots?


On Apr 5, 2019, at 7:13 AM, Jeremy McCormick <notifications@github.com<mailto:notifications@github.com>> wrote:


@bloodyyugo<https://github.com/bloodyyugo>

If this is expected we can work on updating the ref plots. I don't think Norman is back until around April 15.

**Comment by JeremyMcCormick** [comment]
I'll copy the plots to the correct dir Monday and approve the PR.

The PR then needs one additional approval for a merge...

**Review by JeremyMcCormick — APPROVED** [review]
The minor problems which I requested be fixed seem to be resolved.

We will update the reference histograms after merging into master so that the tests work.

I approve.

**Review by normangraf — APPROVED** [review]
Updated reference plots. Good to go.

**Comment by bloodyyugo** [comment]
Great, thanks!


On Apr 8, 2019, at 3:31 PM, normangraf <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #417<https://github.com/JeffersonLab/hps-java/pull/417> into master.

**Pull request merged**
