### PR TITLE
Iss382: fixing form of StandardCuts setters

### PR DESCRIPTION
**Pull request by mdiamon**
Just a change to the form of the code, to bring the StandardCuts setters into compliance with proper style.  No change to the output.

### CODE REVIEW

**Review by JeremyMcCormick — APPROVED** [review]
This looks fine to me.

**Review by bloodyyugo — APPROVED** [review]
Looks ok to me.

**Comment by JeremyMcCormick** [comment]
I see at least one test failure when running the ITs on this branch:

```
checking entries, means and rms for ./BeamspotConstrainedV0Vertices/V0 Bottom Track Momentum
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 491.169 sec <<< FAILURE! - in org.hps.test.it.PhysRun2016V0ReconTest
testIt(org.hps.test.it.PhysRun2016V0ReconTest)  Time elapsed: 491.014 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<4903> but was:<4792>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:234)
        at junit.framework.Assert.assertEquals(Assert.java:241)
        at junit.framework.TestCase.assertEquals(TestCase.java:409)
        at org.hps.test.it.PhysRun2016V0ReconTest.comparePlots(PhysRun2016V0ReconTest.java:93)
        at org.hps.test.it.PhysRun2016V0ReconTest.testIt(PhysRun2016V0ReconTest.java:66)
```

```
$ git status
On branch iss382
Your branch is up to date with 'origin/iss382'.
```

**Review by JeremyMcCormick — APPROVED** [review]
There are test failures but it seems to be due to changes on the master that are not merged into this branch.  When I merge this branch into the master locally, the tests seem to run fine.

**Pull request merged**
