### PR TITLE
Iss455: Add Hodoscope Detector Classes

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
I have added the Hodoscope detector classes to this branch.

To test, run:

```cd detector-model; mvn test -Dtest=HodoscopeConverterTest```

It will print out the information about each Hodoscope pixel.

### CODE REVIEW

**Review by mholtrop — APPROVED** [review]
No errors in the maven tests. 
Code seems fine, but it is difficult to fully test the details.

**Comment by JeremyMcCormick** [comment]
> No errors in the maven tests.
> Code seems fine, but it is difficult to fully test the details.

I don't think it is necessary to check the details of the detector classes/methods/utils for this PR.  The methods are being used extensively in `iss420` from where these files were plucked.  Perhaps they could be looked at more closely when that branch is merged.

**Comment by JeremyMcCormick** [comment]
This needs to be merged before #420 is merged.

**Comment by JeremyMcCormick** [comment]
This is superceded by PR #471.

**Pull request closed without merging**
