### PR TITLE
Allow running reconstruction starting from fitted hits

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by omar-moreno** [comment]
I still need to make a couple of minor changes so please hold off on merging. 

I wanted to put the PR up for people to start testing.

**Comment by normangraf** [comment]
Current tests all pass.

**Comment by pbutti** [comment]
Tested iss701 locally with the feature off and on. Validated that:
- Creates the same SiClusters1D collection size and global location
- Tracks have the same track parameters in each events

**Review by pbutti — CHANGES_REQUESTED** [review]
Resolve conflicts in DataTrackerHitDriver.java

**Comment by normangraf** [comment]
I've added an explicit test for the DataTrackerHitDriver. Enabling debug and comparing the textual output confirms the exact same results. Timing for 100 events is as follows:

Driver                                   0 0.00ms
   RawTrackerHitSensorSetup              100 24.7ms
   RawTrackerHitFitterDriver             100 6.06s
   DataTrackerHitDriver                  100 211ms
   ReadoutCleanupDriver                  100 5.90ms
   *self                                 0 -6.30e+03ms
Loop from raw processed 100 events.
rerunning from LCIO fitted hits
Driver                                   0 0.00ms
   SensorSetup                           100 17.2ms
   *self                                 0 -17.2ms
Loop from fitted LCIO processed 100 events.
Done!

**Review by pbutti — APPROVED** [review]

**Review by normangraf — APPROVED** [review]
Looks to be good to go.

**Pull request merged**
