### PR TITLE
Iss731: Remove events expected to have APV25 readout crosstalk

### LINKED ISSUE #731: 2019 Data: Filter out "Monster Events" during EVIO to LCIO translation.

### PR DESCRIPTION
**Pull request by cbravo135**
This branch was merged with branch iss742. Adding new database table class and adding code for emulation of apv25 readout buffers.

### CODE REVIEW

**Comment by cbravo135** [comment]
Curently this fails a test like this:
```Results :

Failed tests: 
  FEETupleDriverTest.testIt:19->TupleDriverTest.testIt:61->TupleDriverTest.CompareTextFiles:80 new text file is missing branch fspTrkExtrpXSensorStereoTopL9/D
```
On Slack, it seemed multiple people were okay with just removing this test. If @normangraf or @mholtrop can recognize this, I will go ahead and just do that. Quoting Matt G "I’m ok with getting rid of that test".

**Comment by cbravo135** [comment]
FYI, I locally tried removing this test and it compiles and passes all tests with that change. I went ahead and pushed a commit to this branch which removes this test in hopes of expediting this.

**Review by bloodyyugo — APPROVED** [review]
Builds fine and tests are ok...is there anything else I need to do to check this?

**Comment by cbravo135** [comment]
@bloodyyugo you can test the code directly by using the new steering file PhysicsRun2019FullRecon_SvtFilterTest.lcsim and running that on any file in hps_010031. I still don't have the ability to put these new db entires into the server at JLab, but there is an sqlite file at SLAC: hps3/users/bravo/db/hps_conditions_test.db

**Review by mholtrop — APPROVED** [review]
I think Cam's presentations have been quite convincing that this is functioning quite well will very low loss of useful events if any. All the tests pass when merged with master.

**Comment by normangraf** [comment]
Does this code presume that all the events are sequential? Has this been tested on files of skimmed events where this is not the case?

**Comment by cbravo135** [comment]
The code has not been advertised to work on skims. It was actually explicitly stated it won't work on skims, because it would be impossible to do this on skims. This is why the main recon steering file does not use it, and the person running the code should be smart enough to know when and when not to use it.

**Pull request merged**
