### PR TITLE
Alignment dev - WIP

### PR DESCRIPTION
**Pull request by pbutti**
Merge alignment developments into Master branch

### CODE REVIEW

**Review by JeremyMcCormick — DISMISSED** [review]
Please put `makeNewAlignmentIterationLCDD.sh` under `detector-data/src/main/scripts` instead of in the top-level directory.

**Review by normangraf — CHANGES_REQUESTED** [review]
This adds needed functionality.
All the tests run successfully to completion.
I concur with @JeremyMcCormick's request to move the script.
Once that is done I see no reason not to proceed.

**Review by cbravo135 — APPROVED** [review]
IMO, time could be saved when there is a request by this if the reviewer just does the little trivial move themselves if they feel so strongly about it. The move is done.

**Review by normangraf — APPROVED** [review]
Looks good.
All test run successfully to completion.
Looking forward to seeing results from this update.

**Comment by cbravo135** [comment]
This can not be merged until @JeremyMcCormick recognizes the change he requested was made.

**Pull request merged**
