### PR TITLE
added detector HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign

### PR DESCRIPTION
**Pull request by sebouh137**
Alignments from an xml file that Alessandra sent me in an email

### CODE REVIEW

**Comment by omar-moreno** [comment]
@sebouh137 For future reference, when you create a branch, follow the naming convention iss<issue number>. Makes it easier to find the related issue when reviewing a pull request.

**Comment by omar-moreno** [comment]
@afilippi67 Can you verify that the detector uses the correct constants.  It's worth having another pair of eyes on this.

**Comment by afilippi67** [comment]
the file matches my original version, on my account the merge is approved

**Review by omar-moreno — APPROVED** [review]
Alignment constants were verified by @afilippi67 so I approve.

**Pull request merged**
