### PR TITLE
Iss465: Fix error checks on trigger data for 2019 data

### PR DESCRIPTION
**Pull request by JeremyMcCormick**

### CODE REVIEW

**Review by baltzell — APPROVED** [review]

**Review by andrea-celentano — COMMENTED** [review]
This are the commands I used to review this code.

1) git checkout master
2) git pull (this should get the fix #466 that we approved earlier)
3) git merge remotes/origin/iss465
4A) mvn clean
4B) mvn install -DskipTests
5) java -cp /my_path_to/hps-distribution-4.4-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -d HPS-PhysicsRun2016-Pass2 -r -x /org/hps/steering/monitoring/EcalLedSequenceStandalone.lcsim led_data/hpsecal_009004.evio.0000* -b -DoutputFile=009004.histo

The datafile is available at jlab: /work/hallb/hps/data/LED/evio

After doing this, I get again:

Exception in thread "main" java.lang.RuntimeException: No TiTimeOffset condition exists for run 9004
	at org.hps.conditions.trigger.TiTimeOffsetConverter.getData(TiTimeOffsetConverter.java:24)
	at org.hps.conditions.trigger.TiTimeOffsetConverter.getData(TiTimeOffsetConverter.java:11)
	at org.lcsim.conditions.CachedConditionsImplementation.getCachedData(CachedConditionsImplementation.java:20)
	at org.hps.evio.LCSimEngRunEventBuilder.conditionsChanged(LCSimEngRunEventBuilder.java:104)
	at org.lcsim.conditions.ConditionsManagerImplementation.fireConditionsChanged(ConditionsManagerImplementation.java:122)
	at org.lcsim.conditions.ConditionsManagerImplementation.setConditionsReader(ConditionsManagerImplementation.java:69)
	at org.lcsim.conditions.ConditionsManagerImplementation.setDetector(ConditionsManagerImplementation.java:53)
	at org.hps.conditions.database.DatabaseConditionsManager.setDetector(DatabaseConditionsManager.java:801)
	at org.hps.evio.EvioToLcio.checkConditions(EvioToLcio.java:229)
	at org.hps.evio.EvioToLcio.bufferEvents(EvioToLcio.java:202)
	at org.hps.evio.EvioToLcio.run(EvioToLcio.java:514)
	at org.hps.evio.EvioToLcio.main(EvioToLcio.java:92)

Am I doing something wrong here?

-> I figured this out. This branch is "un-doing" what the TI error fix branch implemented. (Why?)

**Review by andrea-celentano — COMMENTED** [review]
Why is this un-doing the fix on TI error (iss #466)?

**Comment by baltzell** [comment]
> Why is this un-doing the fix on TI error (iss #466)?

Yeah, doesn't look right.

**Comment by JeremyMcCormick** [comment]
> > Why is this un-doing the fix on TI error (iss #466)?
> 
> Yeah, doesn't look right.

The file changes look fine to me.

https://github.com/JeffersonLab/hps-java/pull/469/files

I don't see any reversion of the conditions fix.

I'll try to test when I get a chance.

**Comment by baltzell** [comment]
> > > Why is this un-doing the fix on TI error (iss #466)?
> > 
> > 
> > Yeah, doesn't look right.
> 
> The file changes look fine to me.
> 
> https://github.com/JeffersonLab/hps-java/pull/469/files
> 
> I don't see any reversion of the conditions fix.
> 
> I'll try to test when I get a chance.

I think we're confused by 2ccead7

**Comment by JeremyMcCormick** [comment]
I did screw up the branches a bit so maybe there's a bad commit in there.
I'll take a look at it...

**Comment by JeremyMcCormick** [comment]
> > > > Why is this un-doing the fix on TI error (iss #466)?
> > > 
> > > 
> > > Yeah, doesn't look right.
> > 
> > 
> > The file changes look fine to me.
> > https://github.com/JeffersonLab/hps-java/pull/469/files
> > I don't see any reversion of the conditions fix.
> > I'll try to test when I get a chance.
> 
> I think we're confused by [2ccead7](https://github.com/JeffersonLab/hps-java/commit/2ccead768bc35c73f7ca5964c2d234cf25a309a2)

This should be fixed now.

https://github.com/JeffersonLab/hps-java/pull/469/commits/e7d25cabe71625e9b04e86c87cccfc8cd4cd6553

I reverted the revert.  :)

**Review by baltzell — APPROVED** [review]

**Review by andrea-celentano — APPROVED** [review]

**Pull request merged**
