### PR TITLE
added <beamPosZ>-5.0</beamPosZ> into MakeTuples2016.lcsim

### PR DESCRIPTION
**Pull request by sebouh137**

### CODE REVIEW

**Comment by omar-moreno** [comment]
Before this is approved, I want to understand how you concluded that it needs to be at -5 mm.

**Comment by normangraf** [comment]
I agree. See my [comment ](https://github.com/JeffersonLab/hps-java/issues/92#issuecomment-304098111) on the issue.

**Comment by sebouh137** [comment]
I was attempting to make it consistent with what was being used for 2015.  That's where the -5 mm comes from.

**Comment by omar-moreno** [comment]
Norman has already shown that this isn't the case for 2016.

**Comment by normangraf** [comment]
Plotting the unconstrained vertex z position for Møller candidates in the 2016 data does not result in a distribution peaked at -5. How was this number derived for the 2015 data and where is it documented? Before we proceed to reprocess the 2015 data and process the 2016 data I'd like to have a clear understanding of how this number was derived and see that process applied to both data sets.

**Pull request closed without merging**
