### PR TITLE
Change to lcsim 4.2

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
Update to lcsim 4.2 for hps-java release.

### CODE REVIEW

**Review by cbravo135 — DISMISSED** [review]

**Comment by normangraf** [comment]
Waiting for checks to complete, but otherwise should be good to go.

**Comment by cbravo135** [comment]
IMO we should leave the checks part of the review process to the CI. Now we can focus our review efforts in reading the code and understanding what the changes do and leave the check review to github CI. So now PRs would need 2 reviews and passed checks given we have CI now.

**Review by cbravo135 — APPROVED** [review]

**Review by normangraf — APPROVED** [review]

**Comment by JeremyMcCormick** [comment]
I believe this should be merged before #780

**Comment by normangraf** [comment]
I concur that this should be resolved before #780.

**Pull request merged**
