### PR TITLE
Iss735: FEE trigger driver and relative steering file for 2019 MC

### PR DESCRIPTION
**Pull request by tongtongcao**
The FEE trigger driver and the relative steering file are developed for FEE sample of 2019 MC.
In the steering file, # of hits and energy range of Ecal clusters are set for the FEE trigger.

### CODE REVIEW

**Comment by normangraf** [comment]
Fixed the following Checkstyle errors

[INFO] There are 2 errors reported by Checkstyle 6.11.2 with /nfs/slac/g/hps3/users/ngraf/git/hps-java/recon/target/checkst                                     yle-rules.xml ruleset.
[ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[6,8] (imports) UnusedImports: Unused import - java.util                                     .List.
[ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[12,8] (imports) UnusedImports: Unused import - org.hps.                                     record.epics.EpicsData.

**Review by bloodyyugo — DISMISSED** [review]

**Comment by normangraf** [comment]
Matt, did you build and run the tests before approving this request?

**Comment by bloodyyugo** [comment]
Ah, sorry I thought it was just your checkstyle fix....didn't see the first email.

**Comment by bloodyyugo** [comment]
yeah, these test fail badly: 

Failed tests: 
  EngRun2015FeeReconTest.testIt:67->comparePlots:106 expected:<1> but was:<0>
  EngRun2015MollerReconTest.testIt:62->comparePlots:101 expected:<417> but was:<2>
  EngRun2015V0ReconTest.testIt:66->comparePlots:105 expected:<1949> but was:<0>
  PhysRun2016FeeReconTest.testIt:62->comparePlots:89 expected:<125> but was:<0>
  PhysRun2016MollerReconTest.testIt:66->comparePlots:93 expected:<2221> but was:<1770>
  PhysRun2016V0ReconTest.testIt:66->comparePlots:93 expected:<4890> but was:<0>

**Comment by tongtongcao** [comment]
> Fixed the following Checkstyle errors
> 
> [INFO] There are 2 errors reported by Checkstyle 6.11.2 with /nfs/slac/g/hps3/users/ngraf/git/hps-java/recon/target/checkst yle-rules.xml ruleset.
> [ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[6,8] (imports) UnusedImports: Unused import - java.util .List.
> [ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[12,8] (imports) UnusedImports: Unused import - org.hps. record.epics.EpicsData.

**Comment by tongtongcao** [comment]
> Fixed the following Checkstyle errors
> 
> [INFO] There are 2 errors reported by Checkstyle 6.11.2 with /nfs/slac/g/hps3/users/ngraf/git/hps-java/recon/target/checkst yle-rules.xml ruleset.
> [ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[6,8] (imports) UnusedImports: Unused import - java.util .List.
> [ERROR] src/main/java/org/hps/recon/filtering/FEEFilterDriver.java:[12,8] (imports) UnusedImports: Unused import - org.hps. record.epics.EpicsData.

I think that the errors have no business with updates for FEE trigger here.

**Comment by JeremyMcCormick** [comment]
> yeah, these test fail badly:
> 
> Failed tests:
> EngRun2015FeeReconTest.testIt:67->comparePlots:106 expected:<1> but was:<0>
> EngRun2015MollerReconTest.testIt:62->comparePlots:101 expected:<417> but was:<2>
> EngRun2015V0ReconTest.testIt:66->comparePlots:105 expected:<1949> but was:<0>
> PhysRun2016FeeReconTest.testIt:62->comparePlots:89 expected:<125> but was:<0>
> PhysRun2016MollerReconTest.testIt:66->comparePlots:93 expected:<2221> but was:<1770>
> PhysRun2016V0ReconTest.testIt:66->comparePlots:93 expected:<4890> but was:<0>

I can't spot any changes here which would cause such a catastrophe with the recon. Perhaps @tongtongcao just needs to merge in the current master?

**Review by normangraf — APPROVED** [review]
When merged with master all tests pass. Please proceed with PR.

**Review by bloodyyugo — COMMENTED** [review]
tests work now!

**Review by bloodyyugo — APPROVED** [review]

**Pull request merged**
