### PR TITLE
Fix crash for low numbered runs where hodoscope is not initialized.

### PR DESCRIPTION
**Pull request by mholtrop**
Very simple bug fix.

### CODE REVIEW

**Review by JeremyMcCormick — COMMENTED** [review]
This isn't necessary, and I don't think this PR should be approved.  The proper way to fix is just using a valid run number which is not from the Test Run.

**Comment by mholtrop** [comment]
Not fixing this means that the code will not work for _any_ test run data, i.e. all runs with low run numbers. That is OK, in my opinion, but in that case, _all_ test run clutter should simply be ripped out off the code base instead of cluttering up everything. There is no need to keep code in the code base that is broken and we are not willing to accept simple fixes to.

**Comment by JeremyMcCormick** [comment]
Oh, I see now there's a bug, because it's registering a null pointer, so
this fix makes sense.  Thanks for
catching this.

I'm for ripping out Test Run code and tables from
the conditions system as the chance anything works with it now in the
framework is zero, and no one has looked at that data in years.  But now is
probably not the time.

**Review by JeremyMcCormick — APPROVED** [review]

**Comment by mholtrop** [comment]
Hi Jeremy,

Yes, I agree, and I agree this is not the time to decide this, but we can at least not worry about support. We’ll decide officially after the run :-).
We have all he old code in old releases, and a backup of the DB, so if ever there is a really good reason to go back to that data, it will still be possible. 

Best,
	Maurik

**Review by normangraf — APPROVED** [review]

**Pull request merged**
