### PR TITLE
Iss785

### LINKED ISSUE #785: Fix wrongly placed hits in thin sensors and remove strip 0 and 511 from the clustering
Observed a number of hits in the thin sensors that are placed in the wrong locations. 
This showed up clearly in Kalman Tracking routines (originally reported by Robert) 

A dump can be seen here.

PF::Debug::Sensor Name=module_L1t_halfmodule_stereo_sensor0
[ RawHitChecker ] - hit_strip=510
[ RawHitChecker ] - hit cellID=8766028252161
[ RawHitChecker ] - electrode nAxes:2
[ RawHitChecker ] - electrode getNCells:510
[ RawHitChecker ] - electrode getNRows:255
[ RawHitChecker ] - electrode getNColumns:2
[ RawHitChecker ] - electrode getPosition:[      7.0400,      22.500,      0.0000]
[ RawHitChecker ] - striplet  getRowNumber:255
[ RawHitChecker ] - striplet  getColumnNumber:2
[ RawHitChecker ] - striplet  getStripCenter:[      7.0400,      22.500,      0.0000]
[ RawHitChecker ] - striplet  getStripLength:15.0

The columnNumber is wrong (2), should be 1
The position is wrong u should be negative close to -7mm and v should be 7.5mm 
This affects strip 510 (strip 1, 2 and 509 have been checked and are OK) 

Also remove strip 0 and 511 (unbonded strip) from the clustering algorithm.

### PR DESCRIPTION
**Pull request by pbutti**
Fixes wrong hit positioning for strip 510. Fixes clustering for thin sensors removing contributions from strip0 and strip 511

### CODE REVIEW

**Comment by normangraf** [comment]
Let's have a presentation on this at the 02/24 software meeting and then proceed.

**Review by omar-moreno — APPROVED** [review]

**Comment by cbravo135** [comment]
This is a rather small hotfix that would be tough to give much of a presentation on. Omar and PF gave a nice explanation of it during the SVT meeting today, wondering what more @normangraf is looking for?

**Comment by cbravo135** [comment]
IMO, this type of PR should get rolled in ASAP to promote further development.

**Comment by omar-moreno** [comment]
I also don't see the need for a talk.  The issue has been explained extensively at a few meetings now and has been checked out by two people independently. This should be merged in ASAP so we can have Cam generate some MC to start checking other things.

**Comment by normangraf** [comment]
Please proceed.

**Review by cbravo135 — APPROVED** [review]
This code appears to achieve what has been explained in meetings wrt this bug.

**Pull request merged**
