### PR TITLE
Iss783

### LINKED ISSUE #783: Fix backward compatibility of geometry builts fixing the 00 mpid in detector-model classes
The current branch cannot regenerate correctly the lcdd from the compact.xml due to the fact that global structures in the old compact were marked by type 3 and mpid 00. Add a protection for this case and only for the front UChannel.

In particular make sure that:
- Old compacts can be read back from the current branch
- Corrections to the opening angles in the old compact (like opening angle for the front UChannel) are read from a detector of type 3 and sensor number 00
- Back UChannel corrections are kept 0 if not specified in the compact.

### PR DESCRIPTION
**Pull request by pbutti**
Fixes Iss783

### CODE REVIEW

**Review by cbravo135 — APPROVED** [review]
I have verified this works using both HPS-PhysicsRun2019-v2-4pt5 and HPS_Nominal_iter0 running on both data and generating a tritrig+beam file from scratch, all the way to producing plots in the tight selection in hpstr. The two detectors to appear to be identical, as expected.

**Comment by bloodyyugo** [comment]
I get this test failure: 

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.317 sec - in org.hps.test.it.ReadoutToLcioTest

Results :

Failed tests: 
  EngRun2015FeeReconTest.testIt:57->comparePlots:95 expected:<1.2783774159754366> but was:<1.2612191203352578>
  EngRun2015MollerReconTest.testIt:56->comparePlots:93 expected:<417> but was:<384>
  EngRun2015V0ReconTest.testIt:56->comparePlots:93 expected:<1950> but was:<1936>
  PhysRun2016FeeReconTest.testIt:60->comparePlots:85 expected:<124> but was:<115>
  PhysRun2016MollerReconTest.testIt:56->comparePlots:81 expected:<2223> but was:<2126>
  PhysRun2016V0ReconTest.testIt:56->comparePlots:81 expected:<4892> but was:<4884>

**Comment by cbravo135** [comment]
These tests currently fail the same way on master. We are waiting for Norman to update them.

**Comment by cbravo135** [comment]
PF showed these in a meeting and we all agreed the changes were reasonable.

**Review by bloodyyugo — APPROVED** [review]

**Pull request merged**
