### PR TITLE
Various fixes for running the monitoring app

### LINKED ISSUE #508: Database manager incorrectly registers the hodoscopeConverter.
Incorrect logic to only instantiate depending on run number, but then try to register all drivers. This results in registering a null pointer for low run numbers, causing a crash.

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
Fixes #508 and #509.

Also fixes a mysterious issue with connection panel settings with JDK > 1.8.

### CODE REVIEW

**Review by normangraf — APPROVED** [review]
Haven't independently checked this, but I'm OK with proceeding.

**Comment by JeremyMcCormick** [comment]
> Haven't independently checked this, but I'm OK with proceeding.

Well, thank you for your vote of confidence, Norman.  :-)

**Comment by normangraf** [comment]
> > Haven't independently checked this, but I'm OK with proceeding.
> 
> Well, thank you for your vote of confidence, Norman. :-)

You bet! Actually, in the meantime I have built and run all the existing tests, so we're at least not messing with anything that used to work.

But we're creating a horrible rat's nest of issues, some of which are nastily entangled.

**Review by mholtrop — APPROVED** [review]
Tried on a very recent file: hpsnosvt_009228.evio.00000
with the ECalFullMonitoring.settings

Monitoring app works.

**Pull request merged**
