### PR TITLE
Fixing BaseCluster position bug

### LINKED ISSUE #757: BaseCluster objects modify the cluster position
The code in ReconParticleDriver.java uses the following instruction:

     cluster = new BaseCluster(cluster);

while this seems to be very "innocent", actually the BaseCluster object "cluster" obtained in this way as a weird behavior: if one calls cluster.getPosition(), the code is not returning the position of the original cluster passed to the creator method, but performs again the calculation of the position, according to: 

http://www.lcsim.org/sites/lcsim/lcsim-event-model/xref/org/lcsim/event/base/BaseCluster.html
and
 http://www.lcsim.org/sites/lcsim/lcsim-event-model/xref/org/lcsim/event/base/TensorClusterPropertyCalculator.html

This can be fixed by doing:

cluster = new BaseCluster(cluster);
baseClus.setNeedsPropertyCalculation(false);

### PR DESCRIPTION
**Pull request by andrea-celentano**
Fixing issue 757

### CODE REVIEW

**Comment by baltzell** [comment]
Why make the extra object like

```
clusterBase = new BaseCluster(cluster);
clusterBase.setNeedsPropertyCalculation(false);
cluster = clusterBase;
```

rather than 

```
cluster = new BaseCluster(cluster);
cluster.setNeedsPropertyCalculation(false);
```

?

**Comment by baltzell** [comment]
And I guess this means BaseCluster kind of has a bug, in that its copy constructor doesn't fully replicate all the properties.

**Comment by andrea-celentano** [comment]
Reason is that cluster is from the abstract type Cluster, hence when you do

cluster = new BaseCluster(cluster)

you don't have access to the method setNeedsPropertyCalculation. At least, this is what my Eclipse was warning me..

**Comment by baltzell** [comment]
Ah, ok, presumably Cluster inherits from BaseCluster, and you can cast it rather than make an temporary object, but anyway, I can't get to lcsim source currently

**Review by normangraf — APPROVED** [review]
Builds and tests cleanly. Please proceed.

**Review by baltzell — APPROVED** [review]

**Pull request merged**
