### PR TITLE
Iss490: Hodoscope Reconstruction

### PR DESCRIPTION
**Pull request by rafopar**
Please squash this when merging for clean commit message.

----

The hodoscope Reconstruction code.

It reconstructs Hodo Hits from the HodoReadoutHits, and creates:
An LCGenericObject collection named "HodoGenericHits"
It also creates a CalorimeterHit collection named "HodoCalHits"

Then using the HodoGenericHits, it performs clustering, which is comibing hits that are
from the same tile and are in a time coincidence between each other.

### CODE REVIEW

**Comment by rafopar** [comment]
If one wants to run a tes, anc check output, you can go

/w/hallb-scifs17exp/general/hps/rafopar/Hodo_Recon_Tests

Then run a command
java -Xmx1400m -DdisableSvtAlignmentConstants -cp hps-distribution-4.4-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -x ./test_Hodo_Recon.lcsim -d HPS-HodoscopeTest-v1 -R 9000 -DoutputFile=out hpsecal_000084.evio.00000 -n 2000 -e 500

This will produce an output file out.slcio where you can find Hodo recon collections

**Comment by mholtrop** [comment]
The "HodoCalHist" appear to have the energy in units of MeV. I thought that throughout the LCIO file, we had the convention of using GeV, but I am not sure. Could you please check to make sure that it makes sense?

**Comment by rafopar** [comment]
It actually some semi-arbitrary unit.

Since light collection varies as a function the actual hit position, I made a calibration in a way, that
for each tile distributions to peak on 1000.
Please have a look to slides, shown in a collaboration meeting (Slides 9-12)
https://docs.google.com/presentation/d/1O0kYyeWJF0-xZyaS5OW3twa9CNgrT5VLnylcAsLrDLw/edit?usp=sharing

Please let me know, if I need to clarify more staff on this

**Review by mholtrop — APPROVED** [review]
OK, makes sense.

**Review by normangraf — APPROVED** [review]
Appears to work as advertised. All tests pass. Will continue testing once we have integrated 2019 MC simulation and recon.

**Comment by rafopar** [comment]
Thanks Maurik and Normal for reviewing.

I noticed it is giving exception with the
HPS-PhysicsRun2019-beta1-4pt5 detector, while this was fine with the HPS-HodoscopeTest-v1 detector.

I will hold the merging, until this will be cleared.
Asked Kyle to check differences between these two detectors

**Pull request merged**
