### PR TITLE
update readout system for application of DAQ configuration

### LINKED ISSUE #904: Updates for the new readout system with pulser data merging
The new readout system with pulser data merging has been merged into master. Some recent updates for the old readout system, such as application of the DAQ configuration, etc, also need to be taken in the new system.

### PR DESCRIPTION
**Pull request by tongtongcao**
Previously, a new readout system was developed for pulser data merging.
For this PR, the readout system is updated with application of DAQ configuration.
A steering file is developed to process readout with single trigger for MC signal + pulser data as input.

### CODE REVIEW

**Review by bloodyyugo — APPROVED** [review]

**Comment by cbravo135** [comment]
The issue related to this PR is already closed, maybe that should not have been closed?

**Comment by tongtongcao** [comment]
> The issue related to this PR is already closed, maybe that should not have been closed?

The issue is reopened.

**Comment by JeremyMcCormick** [comment]
@tongtongcao Has there been a lot of testing with these changes including running "old" readout configs to make sure they still work fine? Have you compared before/after plots at all? 

Most of the changes look like new code but I think this should be checked anyways.

**Review by JeremyMcCormick — APPROVED** [review]
It looks fine to me based on the fact that the changes are new code for readout overlay or changing of method accessibility. It doesn't appear to me any "old" readout configurations should be effected. I am assuming the updates have been well-tested.

**Comment by tongtongcao** [comment]
> It looks fine to me based on the fact that the changes are new code for readout overlay or changing of method accessibility. It doesn't appear to me any "old" readout configurations should be effected. I am assuming the updates have been well-tested.

It tested well. Actually, it has been applied for MC production with pulser data merging as background

**Pull request merged**
