### PR TITLE
Catch Matrix is singular RuntimeException in GBLRefitterDriver

### PR DESCRIPTION
**Pull request by normangraf**
This one just keeps cropping up. Hope this finally whacks it.
Currently the uncaught Exception causes processing for the rest of the file partition to end.

**This change will need to be merged into the Run2019Master branch right away.**

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
Do you have info for testing this fix like some events that cause the error?

**Comment by normangraf** [comment]
Hello Jeremy,


This event causes the Exception to be thrown for me. I should note that Maurik was unable to replicate the error.


http://www.lcsim.org/test/hps-java/10064_crashingEvent.evio


Norman


________________________________

**Comment by mholtrop** [comment]
I was able to replicate the error using the same steering file that Norman used. So the error depends on the steering file, which is why the DQM is not seeing this error.

**Comment by bloodyyugo** [comment]
Probably happens during 4-hit tracking?  DQM only uses 5-hits

On Jul 31, 2019, at 11:22 AM, Maurik Holtrop <notifications@github.com<mailto:notifications@github.com>> wrote:

I was able to replicate the error using the same steering file that Norman used. So the error depends on the steering file, which is why the DQM is not seeing this error.

**Comment by JeremyMcCormick** [comment]
Thanks, Norman.

Can you paste the full command line you are running to process this file?

**Comment by normangraf** [comment]
Hi Jeremy,

I checked out the Run2019Master branch in a brand-new git repo clone, built the jar and ran the following command-line:

java -Xmx2048m -cp ~/scratch/git/hps-java/distribution/target/hps-distribution-4.4-SNAPSHOT-bin.jar  org.hps.evio.EvioToLcio -x /org/hps/steering/recon/PhysicsRun2019_testRecon.lcsim -r -d HPS-PhysicsRun2019-v1-4pt5 -DoutputFile=x.x 10064_crashingEvent.evio

and I get the following error:

2019-07-30 21:25:04 [INFO] org.lcsim.job.EventMarkerDriver process :: Event 54923446 with sequence 0
Exception in thread "main" java.lang.RuntimeException: Matrix is singular.
       at org.hps.recon.tracking.gbl.matrix.LUDecomposition.solve(LUDecomposition.java:266)
       at org.hps.recon.tracking.gbl.matrix.Matrix.solve(Matrix.java:1018)
       at org.hps.recon.tracking.gbl.matrix.Matrix.inverse(Matrix.java:1038)
       at org.hps.recon.tracking.gbl.GblPoint.getDerivatives(GblPoint.java:468)
       at org.hps.recon.tracking.gbl.GblTrajectory.getFitToKinkJacobian(GblTrajectory.java:444)
       at org.hps.recon.tracking.gbl.GblTrajectory.prepare(GblTrajectory.java:599)
       at org.hps.recon.tracking.gbl.GblTrajectory.construct(GblTrajectory.java:189)
       at org.hps.recon.tracking.gbl.GblTrajectory.<init>(GblTrajectory.java:127)
       at org.hps.recon.tracking.gbl.GblTrajectory.<init>(GblTrajectory.java:22)
       at org.hps.recon.tracking.gbl.HpsGblRefitter.fit(HpsGblRefitter.java:259)
       at org.hps.recon.tracking.gbl.MakeGblTracks.doGBLFit(MakeGblTracks.java:213)
       at org.hps.recon.tracking.gbl.MakeGblTracks.refitTrackWithTraj(MakeGblTracks.java:183)
       at org.hps.recon.tracking.gbl.GBLRefitterDriver.process(GBLRefitterDriver.java:139)
       at org.lcsim.util.Driver.doProcess(Driver.java:261)
       at org.lcsim.util.Driver.processChildren(Driver.java:271)
       at org.lcsim.util.Driver.process(Driver.java:187)
       at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
      at org.lcsim.job.JobControlManager.processEvent(JobControlManager.java:819)
       at org.hps.evio.EvioToLcio.run(EvioToLcio.java:618)
       at org.hps.evio.EvioToLcio.main(EvioToLcio.java:92)

Note that I am running the steering file as a resource, so I haven’t customized anything.

There was some confusion earlier because Maurik reported not seeing this crash, whereas I was freaking out because it pretty much happens every partition. It turns out that he was running a different steering file.

He reports that

java -cp $HPSJAVA org.hps.evio.EvioToLcio  -r -x /org/hps/steering/production/Run2019ReconPlusDataQuality.lcsim -d HPS-PhysicsRun2019-v1-4pt5 -R 10064 -DoutputFile=tmp_test   10064_crashingEvent.evio

runs fine, whereas

java -cp $HPSJAVA org.hps.evio.EvioToLcio  -r -x /org/hps/steering/recon/PhysicsRun2019_testRecon.lcsim -d HPS-PhysicsRun2019-v1-4pt5 -R 10064 -DoutputFile=tmp_test   10064_crashingEvent.evio

gives the matrix singularity error.

So it’s clearly related to the different track-finding strategies being employed in the two steering files.

If you want to clean up the logic in the patch that I committed please feel free to do so. I printed out run and event numbers for the RuntimeException thinking I could at some point come back to fix the underlying problem.

Norman

**Review by omar-moreno — APPROVED** [review]

**Comment by omar-moreno** [comment]
Looks fine.  Need to resolve the conflict but should be merged soon after.

**Comment by mholtrop** [comment]
Superseded by the 688 pull request.

**Pull request closed without merging**
