### PR TITLE
Iss #663 and #662 - Guards around bad SVT hit codes.

### PR DESCRIPTION
**Pull request by mholtrop**
This sets a null pointer guard around the problem reported by Andrea (iss #662). The null propagates so needs to be tested for in several other location. 

Tested on hps_010022.evio.00050 and hps_010022.evio.00107, both files have several thousand events with this error.

### CODE REVIEW

**Comment by pbutti** [comment]
Hi Maurik, 

thank you for this change.
adding the protection looks good to me. However, do we understand why 
HpsSiSensor sensor = this.getSensor(data);
returns null? 

Cheers,
PF

**Comment by mholtrop** [comment]
Hello PF,

I hope that Omar will look into this. He is aware of the issue, but I don’t know when he will have time for this.

Best,
	Maurik

**Review by pbutti — APPROVED** [review]

**Comment by pbutti** [comment]
Fine for me, then

**Comment by rafopar** [comment]
I din't have much to say, except the integration test run just fine

**Review by rafopar — APPROVED** [review]
Integration test run just fine.

As I am not expert in this part. I am just approving it.

**Pull request merged**
