### PR TITLE
Iss677 - Layer 0/1 changes and 2019 trigger drivers

### LINKED ISSUE #677: Validation 2019 Readout and Reconstruction Pipeline
The branch associated with this issue will be used to validate the updates needed for L0/1 of the SVT and the trigger sim.

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Review by normangraf — APPROVED** [review]
Builds and tests fine, so at least it doesn't break anything (that we're testing...). There are a LOT of changes in this request so I think we should continue performance testing after the merge.

**Review by pbutti — APPROVED** [review]

**Comment by pbutti** [comment]
I cannot speak much about all the trigger part. For the recon part things look ok. Only doubt is the current settings for the "firstLayer" in the KalmanPatRecHPS that is now set to "0", probably breaking 2016 proper pattern reco at the moment.

**Comment by normangraf** [comment]
Layering starts at 1.

**Comment by pbutti** [comment]
It's a different numbering what I'm talking about.
In the KF pat reco, numbering starts at 0 and ends to 13.

**Pull request merged**
