### PR TITLE
Iss304: Add chart pop-up capability

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
- Add pop-up of current region if clicked (can be toggled on/off as option in Plot menu)

- Removed hard-coded pop-up listeners from SVT plots

- Minor cleanup and formatting changes

- Change the jfree-aida dependency to 1.9.0 release from 1.9-SNAPSHOT

I checked that the new functionality works with the SVT occupancy plots on run 5772 data.

### CODE REVIEW

**Review by mholtrop — COMMENTED** [review]
Appears to be working, but I cannot seem to get any data into the plots. I don't have time to check each and every monitoring config file to see which ones work with 2015 or 2016 data.
Please suggest a config and data file combo.

**Comment by JeremyMcCormick** [comment]
Did you try engrun2015 data (run 5772) with SVT occupancy plots?

**Comment by mholtrop** [comment]
I tried java -Xmx1g -cp  distribution/target/hps-distribution-4.1-SNAPSHOT-bin.jar  org.hps.monitoring.application.Main -c setting.prop

With setting.prop:

DetectorName=HPS-EngRun2015-Nominal-v7-0-fieldmap
DisconnectOnError=true
DisconnectOnEndRun=true
EventBuilderClassName=org.hps.evio.LCSimEngRunEventBuilder
#LogFileName=
LogLevel=ALL
LogLevelFilter=ALL
LogToFile=false
MaxEvents=-1
#SteeringFile=
SteeringResource=org/hps/steering/monitoring/SVTMonitoring.lcsim
SteeringType=RESOURCE

# event source
DataSourceType=ET_SERVER
#DataSourcePath=
ProcessingStage=LCIO
 
# ET connection settings
# FIXME: These should really all be prepended by 'Et' so their purpose is clear.
Blocking=false
EtName=ETBuffer
ChunkSize=1
Host=localhost
Port=11111
StationPosition=1
Prescale=1
QueueSize=0
StationName=MY_STATION
Verbose=false
WaitMode=TIMED
WaitTime=1000000000


I did notice the following error:

java.lang.ArrayIndexOutOfBoundsException: 11
	at org.hps.monitoring.drivers.svt.SVTHitReconstructionPlots.process(SVTHitReconstructionPlots.java:220)
	at org.lcsim.util.Driver.doProcess(Driver.java:261)
	at org.lcsim.util.Driver.processChildren(Driver.java:271)
	at org.lcsim.util.Driver.process(Driver.java:187)
	at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
	at org.hps.record.composite.LcioEventAdapter.recordSupplied(LcioEventAdapter.java:116)
	at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.hps.record.composite.CompositeLoop.loop(CompositeLoop.java:208)
	at org.hps.record.composite.EventProcessingThread.run(EventProcessingThread.java:66)

**Comment by mholtrop** [comment]
SvtOnlineMonitoring.lcsim does work.
Popups are great!

**Comment by JeremyMcCormick** [comment]
> I tried java -Xmx1g -cp  distribution/target/hps-distribution-4.1-SNAPSHOT-bin.jar org.hps.monitoring.application.Main -c setting.prop
> [etc.]

I noticed this error too, but I am not sure that it is anything to do with the monitoring.  Rather it is probably something that has been updated in the reconstruction which has not been propagated to the monitoring driver.  Probably bears further investigation though.

**Review by mholtrop — APPROVED** [review]
Works when tested on org/hps/steering/monitoring/SvtOnlineMonitoring.lcsim

**Comment by JeremyMcCormick** [comment]
@mholtrop If you `git pull` and recompile there is only one pop-up window that shows at a time now.

**Pull request merged**
