### PR TITLE
Iss301: SVT Hit level plots

### PR DESCRIPTION
**Pull request by mrsolt**
Standardizing SVT Hit level plots for quick and easy use.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
@mrsolt How can I produce these plots?  Is there are steering available or can you provide one?  And which input data?

**Comment by JeremyMcCormick** [comment]
@mrsolt 

This is the steering I assume?

```
/org/hps/steering/analysis/SVTHitPlots.lcsim
```

Can you point me to an input file so I can produce these plots?

**Comment by mrsolt** [comment]
Jeremy, there are instructions here: https://confluence.slac.stanford.edu/display/hpsg/Plots+for+SVT+NIM


You can make my hit level plots and vertexing plots. It should tell you what files to use.


Matt Solt

________________________________

**Review by normangraf — APPROVED** [review]
Analysis level, should not affect any other code.

**Review by mholtrop — APPROVED** [review]
All in analysis, so fine to merge.

**Pull request merged**
