### PR TITLE
Move the track extrapolation from dipole edge to z=800

### LINKED ISSUE #1026: Track extrapolation to ECAL fix
As documented by Alic, Norman, and Lewis the track state at the ECAL is not computed properly. 
This issue is to fix the problem.

### PR DESCRIPTION
**Pull request by pbutti**
This should fix #1026 
@mholtrop

### CODE REVIEW

**Review by bloodyyugo — CHANGES_REQUESTED** [review]
One of the tests is failing

**Comment by mholtrop** [comment]
> One of the tests is failing

Error:    PhysRun2016V0ReconTest>ReconTest.testRecon:380->ReconTest.comparePlots:252->ReconTest.compareTrees:272->ReconTest.compareHistograms:293 Bin 12 is different for: V0 Bottom Track Momentum expected:<241> but was:<240>

So that is because our tests are not very smart and do not permit improvements of the code.

**Comment by pbutti** [comment]
@mholtrop 
Can we change the reference with the new file?

**Comment by mholtrop** [comment]
>  Can we change the reference with the new file?

We should be able to, I think. I know how though.

**Comment by pbutti** [comment]
This PR is linked to #1031

**Comment by cbravo135** [comment]
Just want to point out that there isn't a need to request changes when a test is failing since that already blocks the merge anyway.

**Comment by cbravo135** [comment]
I updated the reference file, the tests are all passing for this branch now.

**Review by cbravo135 — APPROVED** [review]
Nice clean way to do this.

**Review by bloodyyugo — APPROVED** [review]

**Pull request merged**
