### PR TITLE
adding return null to MakeGBLTracks

### PR DESCRIPTION
**Pull request by mrsolt**
I simply added a "return null" in a function in MakeGblTracks so that if the GBL refit fails it doesn't crash the whole code.

### CODE REVIEW

**Comment by normangraf** [comment]
@bloodyyugo can you simply check this out and see if it builds and tests cleanly?

**Review by normangraf — COMMENTED** [review]
I don't understand why I see the following file differences:

git checkout master
git pull
git checkout iss426
git pull
git diff --name-status master
M       analysis/src/main/java/org/hps/analysis/tuple/TupleMaker.java
M       analysis/src/main/java/org/hps/analysis/tuple/VertexDebugTupleDriver.java
D       analysis/src/main/java/org/hps/analysis/tuple/VertexTupleDriver.java
M       recon/src/main/java/org/hps/recon/particle/HpsReconParticleDriver.java
M       recon/src/main/java/org/hps/recon/vertexing/BilliorVertex.java
M       recon/src/main/java/org/hps/recon/vertexing/BilliorVertexer.java
M       steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullRecon.lcsim
D       steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullReconLocal.lcsim
M       tracking/src/main/java/org/hps/recon/tracking/RawTrackerHitFitterDriver.java
M       tracking/src/main/java/org/hps/recon/tracking/gbl/MakeGblTracks.java

**Comment by bloodyyugo** [comment]
I think I get the same thing…

[PPA-PC91391-3:~/hps/fooblah] %git diff --name-status master
M       analysis/src/main/java/org/hps/analysis/tuple/TupleMaker.java
M       analysis/src/main/java/org/hps/analysis/tuple/VertexDebugTupleDriver.java
D       analysis/src/main/java/org/hps/analysis/tuple/VertexTupleDriver.java
M       recon/src/main/java/org/hps/recon/particle/HpsReconParticleDriver.java
M       recon/src/main/java/org/hps/recon/vertexing/BilliorVertex.java
M       recon/src/main/java/org/hps/recon/vertexing/BilliorVertexer.java
M       steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullRecon.lcsim
D       steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullReconLocal.lcsim
M       tracking/src/main/java/org/hps/recon/tracking/RawTrackerHitFitterDriver.java
M       tracking/src/main/java/org/hps/recon/tracking/gbl/MakeGblTracks.java


….

On Apr 9, 2019, at 5:02 PM, normangraf <notifications@github.com<mailto:notifications@github.com>> wrote:


@normangraf commented on this pull request.

I don't understand why I see the following file differences:

git checkout master
git pull
git checkout iss426
git pull
git diff --name-status master
M analysis/src/main/java/org/hps/analysis/tuple/TupleMaker.java
M analysis/src/main/java/org/hps/analysis/tuple/VertexDebugTupleDriver.java
D analysis/src/main/java/org/hps/analysis/tuple/VertexTupleDriver.java
M recon/src/main/java/org/hps/recon/particle/HpsReconParticleDriver.java
M recon/src/main/java/org/hps/recon/vertexing/BilliorVertex.java
M recon/src/main/java/org/hps/recon/vertexing/BilliorVertexer.java
M steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullRecon.lcsim
D steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullReconLocal.lcsim
M tracking/src/main/java/org/hps/recon/tracking/RawTrackerHitFitterDriver.java
M tracking/src/main/java/org/hps/recon/tracking/gbl/MakeGblTracks.java

**Review by normangraf — APPROVED** [review]
I approve pending a successful Jenkins test build. @JeremyMcCormick feel free to approve this when it finishes.

**Review by JeremyMcCormick — APPROVED** [review]
The ITs all pass.  I approve.

**Pull request merged**
