### PR TITLE
Iss309

### PR DESCRIPTION
**Pull request by normangraf**
Adding two new Drivers for tracking performance.

### CODE REVIEW

**Comment by normangraf** [comment]
This is an incremental pull request. Please do not delete this branch after merging.

**Comment by JeremyMcCormick** [comment]
Should #309 be closed after this is merged or you are continuing to work on it?

Any reason this needs to be merged before you are done working on this particular branch?  (just wondering)

**Comment by normangraf** [comment]
Hi Jeremy,

No need to merge yet. Still working on it. I just wanted to push an intermediate step, but anyone interested can just check this out.

Norman

**Comment by JeremyMcCormick** [comment]
@normangraf @mholtrop 

This PR is going on a year now.  Should it be merged or taken down?

It seems like mostly new code to me so I would vote for merging it soon as it doesn't seem like it should affect existing recon output.

Also, there's a conflict that's been introduced with a compact XML file and the .gitignore file though I assume these are easily resolved by merging in master to the branch and resolving the files.

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
Conflicts need to be resolved before the branch can be merged.

**Comment by JeremyMcCormick** [comment]
I'm going to close this as it is over a year old.  

@normangraf Please put up a new PR if you want it merged.

**Comment by normangraf** [comment]
I concur


________________________________

**Pull request closed without merging**
