### PR TITLE
Add tanLambda cuts

### PR DESCRIPTION
**Pull request by sarahgaiser**
work in progress

### CODE REVIEW

**Comment by pbutti** [comment]
Hi Sarah, the cuts should be done at track reconstruction level instead at plotting level. 
Making cuts at track reconstruction level (i.e. SimpleGBLTrajAliDriver) would harmonize what is used for alignment and what is used for monitoring. 
In fact the tanLambda cuts can already be applied at that stage see:
https://github.com/JeffersonLab/hps-java/blob/master/tracking/src/main/java/org/hps/recon/tracking/gbl/SimpleGBLTrajAliDriver.java#L352

**Comment by cbravo135** [comment]
Hi PF, there are times when I personally run GBLOutputDriver and not SimpleGBLTrajAliDriver, and would like to be able to have these kinds of cuts possible there too.

**Comment by pbutti** [comment]
Is it clear why CI fails?

**Comment by cbravo135** [comment]
Relaunched CI and they passed. @pbutti

**Review by cbravo135 — APPROVED** [review]

**Review by pbutti — APPROVED** [review]

**Pull request merged**
